# Generated by Django 2.1.4 on 2019-01-26 18:10

import django.core.validators
from django.db import migrations
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20190123_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=posts.models.CICharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_tagname', message='Can contain only alphabets, numerals or -', regex='^[0-9a-zA-Z ]+$')]),
        ),
    ]
