# Generated by Django 2.1.4 on 2019-03-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_subscribedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='email',
            field=models.EmailField(error_messages={'unique': 'You are already subscribed'}, max_length=100, unique=True),
        ),
    ]
