# Generated by Django 2.1.4 on 2019-03-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_subscribedusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMailIdMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('email_hash', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='subscribedusers',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
