# Generated by Django 2.1.4 on 2019-03-25 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190311_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets are allowed.')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabets are allowed.')])),
                ('email', models.EmailField(error_messages={'unique': 'This email has already been used'}, max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('liked_posts', models.ManyToManyField(related_name='liked_posts', to='posts.Post')),
                ('saved_posts', models.ManyToManyField(related_name='saved_posts', to='posts.Post')),
            ],
        ),
    ]
