# Generated by Django 2.1.4 on 2019-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_usermailidmap_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been used'}, max_length=200, unique=True),
        ),
    ]
